name: Deploy Infrastructure with Approval

on:
  workflow_dispatch:  # Manual trigger (can change to push)

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Dev)
        run: terraform -chdir=environments/dev init

      - name: Terraform Plan (Dev)
        run: terraform -chdir=environments/dev plan -var-file="terraform.tfvars" -out=tfplan

      - name: Terraform Apply (Dev)
        run: terraform -chdir=environments/dev apply -auto-approve tfplan

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: 
      name: prod
    needs: deploy-dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Prod)
        run: terraform -chdir=environments/prod init

      - name: Terraform Plan (Prod)
        run: terraform -chdir=environments/prod plan -var-file="terraform.tfvars" -out=tfplan

      - name: Terraform Apply (Prod)
        run: terraform -chdir=environments/prod apply -auto-approve tfplan
